/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadeproductos.view;

import com.mycompany.sistemadeproductos.controller.ProductoController;
import com.mycompany.sistemadeproductos.model.Producto;


/**
 *
 * @author Cohorte 5
 */
public class ResumenInventario extends javax.swing.JFrame {
    
    private ProductoController productoController;
    /**
     * Creates new form ResumenInventario
     */
    public ResumenInventario(ProductoController productoController) {     
        initComponents();
        setLocationRelativeTo(null);

        this.productoController = productoController;

        cargarResumen();
    }
    
    private void cargarResumen() {

        int cantidadTotal = productoController.obtenerCantidadProductos();

        int cantidadFisicos = productoController.obtenerCantidadProductosFisicos();

        int cantidadDigitales = productoController.obtenerCantidadProductosDigitales();

        int cantidadActivos = productoController.obtenerCantidadProductosActivos();

        int cantidadInactivos  = productoController.obtenerCantidadProductosInactivos();

        double valorTotal = productoController.calcularValorTotalInventario();

        Producto productoMayor = productoController.obtenerProductoMayorPrecio();

        Producto productoMenor = productoController.obtenerProductoMenorPrecio();
        
        // Cantidades
        ValorTotalProductos.setText(
                String.valueOf(cantidadTotal)
        );

        ValorTotalProductosFisicos.setText(
                String.valueOf(cantidadFisicos)
        );

        ValorTotalProductosDigitales.setText(
                String.valueOf(cantidadDigitales)
        );

        ValorTotalProductosActivos.setText(
                String.valueOf(cantidadActivos)
        );

        ValorTotalProductosInactivos.setText(
                String.valueOf(cantidadInactivos)
        );

        ValorTotalInventario.setText(
                String.format("$%,.2f", valorTotal)
        );

        // Producto con mayor precio
        if (productoMayor != null) {

            ValorCodigoProductoMayor.setText(
                    productoMayor.getCodigo()
            );

            ValorNombreProductoMayor.setText(
                    productoMayor.getNombre()
            );

            ValorPrecioFinalMayor.setText(
                    String.format(
                            "$%,.2f",
                            productoMayor.calcularPrecioFinal()
                    )
            );

        } else {

            ValorCodigoProductoMayor.setText("-");
            ValorNombreProductoMayor.setText("-");
            ValorPrecioFinalMayor.setText("$0.00");
        }

        // Producto con menor precio
        if (productoMenor != null) {

            ValorCodigoProductoMenor.setText(
                    productoMenor.getCodigo()
            );

            ValorNombreProductoMenor.setText(
                    productoMenor.getNombre()
            );

            ValorPrecioFinalMenor.setText(
                    String.format(
                            "$%,.2f",
                            productoMenor.calcularPrecioFinal()
                    )
            );

        } else {

            ValorCodigoProductoMenor.setText("-");
            ValorNombreProductoMenor.setText("-");
            ValorPrecioFinalMenor.setText("$0.00");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TotalProductos = new javax.swing.JLabel();
        ValorTotalProductos = new javax.swing.JLabel();
        TotalProductosFisicos = new javax.swing.JLabel();
        ValorTotalProductosFisicos = new javax.swing.JLabel();
        TotalProductosDigitales = new javax.swing.JLabel();
        ValorTotalProductosDigitales = new javax.swing.JLabel();
        TotalProductosActivos = new javax.swing.JLabel();
        ValorTotalProductosActivos = new javax.swing.JLabel();
        TotalProductosInactivos = new javax.swing.JLabel();
        ValorTotalProductosInactivos = new javax.swing.JLabel();
        TotalInventario = new javax.swing.JLabel();
        ValorTotalInventario = new javax.swing.JLabel();
        ProductoMayorPrecio = new javax.swing.JLabel();
        NombreProductoMayor = new javax.swing.JLabel();
        ValorNombreProductoMayor = new javax.swing.JLabel();
        CodigoProductoMayor = new javax.swing.JLabel();
        ValorCodigoProductoMayor = new javax.swing.JLabel();
        PrecioFinalMayor = new javax.swing.JLabel();
        ValorPrecioFinalMayor = new javax.swing.JLabel();
        ProductoMenorPrecio = new javax.swing.JLabel();
        NombreProductoMenor = new javax.swing.JLabel();
        ValorNombreProductoMenor = new javax.swing.JLabel();
        CodigoProductoMenor = new javax.swing.JLabel();
        ValorCodigoProductoMenor = new javax.swing.JLabel();
        PrecioFinalMenor = new javax.swing.JLabel();
        ValorPrecioFinalMenor = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Resumen de inventario");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Resumen de inventario");

        TotalProductos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TotalProductos.setText("Total de productos:");

        ValorTotalProductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ValorTotalProductos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        TotalProductosFisicos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TotalProductosFisicos.setText("Total de productos físicos:");

        ValorTotalProductosFisicos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ValorTotalProductosFisicos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        TotalProductosDigitales.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TotalProductosDigitales.setText("Total de productos digitales:");

        ValorTotalProductosDigitales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ValorTotalProductosDigitales.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        TotalProductosActivos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TotalProductosActivos.setText("Total de productos activos:");

        ValorTotalProductosActivos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ValorTotalProductosActivos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        TotalProductosInactivos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TotalProductosInactivos.setText("Total de productos Inactivos:");

        ValorTotalProductosInactivos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ValorTotalProductosInactivos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        TotalInventario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TotalInventario.setText("Valor total de inventario:");

        ValorTotalInventario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ValorTotalInventario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        ProductoMayorPrecio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProductoMayorPrecio.setText("Producto con mayor precio:");

        NombreProductoMayor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NombreProductoMayor.setText("Nombre:");

        ValorNombreProductoMayor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ValorNombreProductoMayor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        CodigoProductoMayor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CodigoProductoMayor.setText("Codigo:");

        ValorCodigoProductoMayor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ValorCodigoProductoMayor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        PrecioFinalMayor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PrecioFinalMayor.setText("Precio Final:");

        ValorPrecioFinalMayor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ValorPrecioFinalMayor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        ProductoMenorPrecio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProductoMenorPrecio.setText("Producto con menor precio final:");

        NombreProductoMenor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NombreProductoMenor.setText("Nombre:");

        ValorNombreProductoMenor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ValorNombreProductoMenor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        CodigoProductoMenor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CodigoProductoMenor.setText("Codigo:");

        ValorCodigoProductoMenor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ValorCodigoProductoMenor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        PrecioFinalMenor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PrecioFinalMenor.setText("Precio Final:");

        ValorPrecioFinalMenor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ValorPrecioFinalMenor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NombreProductoMayor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ValorNombreProductoMayor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CodigoProductoMayor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ValorCodigoProductoMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NombreProductoMenor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ValorNombreProductoMenor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CodigoProductoMenor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ValorCodigoProductoMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TotalProductosFisicos)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(TotalProductos)
                                        .addGap(169, 169, 169)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ValorTotalProductosFisicos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ValorTotalProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TotalProductosDigitales)
                                    .addComponent(TotalProductosActivos)
                                    .addComponent(TotalProductosInactivos)
                                    .addComponent(TotalInventario)
                                    .addComponent(ProductoMayorPrecio)
                                    .addComponent(ProductoMenorPrecio)
                                    .addComponent(PrecioFinalMayor))
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ValorPrecioFinalMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ValorTotalInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ValorTotalProductosInactivos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ValorTotalProductosDigitales, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ValorTotalProductosActivos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Regresar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(PrecioFinalMenor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ValorPrecioFinalMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(TotalProductos))
                    .addComponent(ValorTotalProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TotalProductosFisicos)
                    .addComponent(ValorTotalProductosFisicos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TotalProductosDigitales)
                        .addGap(21, 21, 21)
                        .addComponent(TotalProductosActivos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ValorTotalProductosDigitales, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ValorTotalProductosActivos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(TotalProductosInactivos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ValorTotalProductosInactivos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TotalInventario)
                        .addGap(18, 18, 18)
                        .addComponent(ProductoMayorPrecio))
                    .addComponent(ValorTotalInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreProductoMayor)
                    .addComponent(ValorNombreProductoMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoProductoMayor)
                    .addComponent(ValorCodigoProductoMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ValorPrecioFinalMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecioFinalMayor))
                .addGap(20, 20, 20)
                .addComponent(ProductoMenorPrecio)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NombreProductoMenor)
                        .addGap(18, 18, 18)
                        .addComponent(CodigoProductoMenor)
                        .addGap(18, 18, 18)
                        .addComponent(PrecioFinalMenor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(Regresar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ValorNombreProductoMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ValorCodigoProductoMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ValorPrecioFinalMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResumenInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResumenInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResumenInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResumenInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResumenInventario().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CodigoProductoMayor;
    private javax.swing.JLabel CodigoProductoMenor;
    private javax.swing.JLabel NombreProductoMayor;
    private javax.swing.JLabel NombreProductoMenor;
    private javax.swing.JLabel PrecioFinalMayor;
    private javax.swing.JLabel PrecioFinalMenor;
    private javax.swing.JLabel ProductoMayorPrecio;
    private javax.swing.JLabel ProductoMenorPrecio;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel TotalInventario;
    private javax.swing.JLabel TotalProductos;
    private javax.swing.JLabel TotalProductosActivos;
    private javax.swing.JLabel TotalProductosDigitales;
    private javax.swing.JLabel TotalProductosFisicos;
    private javax.swing.JLabel TotalProductosInactivos;
    private javax.swing.JLabel ValorCodigoProductoMayor;
    private javax.swing.JLabel ValorCodigoProductoMenor;
    private javax.swing.JLabel ValorNombreProductoMayor;
    private javax.swing.JLabel ValorNombreProductoMenor;
    private javax.swing.JLabel ValorPrecioFinalMayor;
    private javax.swing.JLabel ValorPrecioFinalMenor;
    private javax.swing.JLabel ValorTotalInventario;
    private javax.swing.JLabel ValorTotalProductos;
    private javax.swing.JLabel ValorTotalProductosActivos;
    private javax.swing.JLabel ValorTotalProductosDigitales;
    private javax.swing.JLabel ValorTotalProductosFisicos;
    private javax.swing.JLabel ValorTotalProductosInactivos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
